#!/usr/bin/env python3
"""normalize_libs.py

A script to collect IINA's libs & their transitive libs, then consolidate similar versions & normalize their paths for
use in the app bundle. This is needed to avoid multiple versions of the same lib being bundled, which is more difficult
to integrate into Xcode builds. Fixing the rpaths is also needed to replace hard-coded paths to the nix store with
relative paths within the app bundle.

Pseudocode:
-----------
let name_variants_map = [base_id -> [name_variant -> variant_full_path]]
let canonical_name_map = [base_id -> canonical_name]
For all deps, build name_variants_map:
1. Find base_id from dep
2. Add to name_variants_map

For all entries in name_variants_map, build canonical_name_map:
1. For each base_id, determine best canonical_name:
   Use most specific version available: split by dots. Verify that no major differences in vesions found!
2. Store best variant name in canonical_name_map
3. Copy best variant to frameworks_staging

For all files in frameworks_staging:
1. Fix nixpath rpaths. Need to extract base_id for each & rewrite to use best variant! 
2. Fix any other rpaths needed
"""

import os
import re
import sys
import stat
import subprocess
import shutil
from typing import Optional

# If specified as the first arg, search for all /nix/store refrences in the second arg, print them, then exit
# without doing any modifications. This is useful for debugging & verifying lib references after a build.
PRINT_PATHS_ONLY_ARG = "--print-only"

LC_RPATH: str = '@executable_path/../Frameworks'

# Set of lib IDs to exclude.
# Do not include Swift concurrency library.
# Also skip 'libffi-trampoline' (apparently a typo of 'libffi-trampolines'?)
BLACKLIST: set[str] = {'libswift_Concurrency', 'libffi-trampoline'}

# Simplifies a version string by removing any trailing '.0' segments.
def simplify_version(full_version: str) -> str:
  version = full_version
  while version.endswith('.0'):
    version = version[:-2]
  return version

def parse_base(file_path: str) -> Optional[tuple[str, str]]:
    basename = os.path.basename(file_path)
    name_tokens = basename.split('.')
    if name_tokens:
        return (basename, name_tokens[0])
    
    print(f"⚠️ Could not derive base ID from path: {file_path}")
    return None

# Set given file R+W by the owner.
def ensure_writable(file_path: str):
	os.chmod(file_path, stat.S_IRUSR | stat.S_IWUSR)

def ls_files_in_dir(dir_path: str):
  all_children: list[tuple[str, str]] = map(lambda base_name: (base_name, os.path.join(dir_path, base_name)), os.listdir(dir_path))
  return [child for child in all_children if os.path.isfile(child[1])]

def ensure_rpath(lib_path: str):
  result = subprocess.run(['otool', '-l', lib_path], capture_output=True, text=True)
  for line in result.stdout.splitlines():
    if LC_RPATH in line:
      print(f'✅ LC_RPATH present → {lib_path}')
      return
  
  print(f'➕ LC_RPATH {LC_RPATH} → {lib_path}')
  subprocess.run(['install_name_tool', '-add_rpath', LC_RPATH, lib_path])
  
# Return `otool -L` stdouut output as list of lines for given bin_path (Mach-O lib or executable binary)
def otool_list_shared_libs(bin_path: str) -> list[str]:
  otool_result = subprocess.run(['otool', '-L', bin_path], capture_output=True, text=True)
  return otool_result.stdout.splitlines()

# Gets lib references in the given Mach-O lib or executable binary whose path starts with '/nix/store/'. 
# Returns a list of tuples containing: (reference_path, compatibility_version, current_version)
def otool_find_nix_libs(bin_path: str) -> list[(str, str, str)]:
  nix_libs: list[(str, str, str)] = []
  for line in otool_list_shared_libs(bin_path):
    # Skip header lines which contain the source file path.
    # We are interested in the lines under them which are indented.
    if len(line) > 0 and line[0].isspace():
      pattern = r'(.*) \(compatibility version ([^,]+), current version ([^\)]+)\)'
      match = re.match(pattern, line.strip())
      if not match:
        continue
      ref_path = match.group(1)
      
      # We only care about local libs, which start out generated by Nix
      if not ref_path.startswith('/nix/store/'):
        continue
      
      compat_version = simplify_version(match.group(2))
      current_version = simplify_version(match.group(3))
      nix_libs.append((ref_path, compat_version, current_version))
    
  return nix_libs
  
def rewrite_lib_entry(current_entry: str, to: str, bin_path: str):
  subprocess.run(['install_name_tool', '-change', current_entry, to, bin_path], capture_output=False, text=True)

#--- MAIN ---#

def main():
  if len(sys.argv) < 3:
    print(f'usage: iina-normalize-app /path/to/IINA.app /path/to/IINA.app/ContentsFrameworks')
    print(f'   or: iina-normalize-app {PRINT_PATHS_ONLY_ARG} /path/to/IINA.app/ContentsFrameworks')
    exit(1)

  print_nix_paths_then_exit = sys.argv[1] == PRINT_PATHS_ONLY_ARG
  app_path = sys.argv[1]
  frameworks_path = sys.argv[2]
  
  # FIRST PASS: Scan all libs; collecting dependency metadata to populate name_variants_map
  # {base_id: {variant_basename: {variant_compatibility_version: variant_full_path}}}
  # By assembling the data first, we can elimminate the (many) duplicates before doing ELF work which will speed things
  # up greatly.
  name_variants_map: dict[str, dict[str, dict[str, str]]] = {}
  libs_searched: dict[str, bool] = {}
  
  for _, file_path in ls_files_in_dir(frameworks_path):
    if not (file_path.endswith('.dylib') or file_path.endswith('.so')):
      continue
    libs_searched[file_path] = False
    
  while True:
    files_to_search = [path for path, searched in libs_searched.items() if not searched]
    if not files_to_search:
      break
    
    for file_path in files_to_search:
      libs_searched[file_path] = True
      
      (_, base_id) = parse_base(file_path)
      if not base_id:
        continue
      # See notes for blacklist above
      if base_id in BLACKLIST:
        print(f'File is in blacklist, skipping: {file_path}')
        continue
      
      # Here we want to get a survey of *all* canonical libs which need to be modified
      for ref_path, compat_version, current_version in otool_find_nix_libs(file_path):
        print(f'Found ref: {ref_path} → {compat_version} / {current_version}')
        (ref_basename, base_id) = parse_base(ref_path)
        if not base_id:
          continue
        if base_id in BLACKLIST:
          print(f'Ref is in blacklist, skipping: {ref_path}')
          continue
        if libs_searched.get(ref_path, False):
          # print(f'Ref already checked, skipping: {ref_path}')
          continue
        # Need to search this ref for any transitive refs:
        libs_searched[ref_path] = False

        variants_map = name_variants_map.get(base_id, dict())
        variant_versions_map = variants_map.get(compat_version, dict())
        variant_versions_map[ref_basename] = ref_path
        variants_map[compat_version] = variant_versions_map
        name_variants_map[base_id] = variants_map
 
  for base_id, variants in name_variants_map.items():
    print(f'Variants of lib {base_id}: {variants}')
  
  if print_nix_paths_then_exit:
    print(f"⚠️ Exiting script now without modifying any files, as {PRINT_PATHS_ONLY_ARG} arg was provided.")
    return
  
  # Only needed if multiple versions found for the same ID. Map of {canonical_name: variant_path}.
  # This is needed when we are using a canonical name which we have created ourself, which breaks our ability to look
  # up the path of its source variant in name_variants_map.
  rename_map: dict[str, str] = {}
  # Determine the best canonical name for each item in name_variants_map, populate canonical_name_map.
  # canonical_name_map = {base_id: {compat_version: canonical_name}}
  # Note: all versions must be simplified using simplify_version()! Otherwise string-based comparisons will fail.
  canonical_name_map: dict[str, dict[str, str]] = {}
  for base_id, variants_map in name_variants_map.items():
    multiple_versions_found = len(variants_map) > 1
    if multiple_versions_found:
      print(f'Found multiple variants for {base_id}: {variants_map.keys()}')

    for variant_compat_ver, variant_versions_map in variants_map.items():
      # Determine the best canonical name (most specific version)
      best_variant_name: str = ''
      best_variant_specificity: int = 0
      for variant_name, _ in variant_versions_map.items():
        specificity = len(variant_name.split('.'))
        if specificity > best_variant_specificity:
          best_variant_specificity = specificity
          best_variant_name = variant_name
          
      if multiple_versions_found:
        # 2026-05-06 This is a workaround for a libiconv dependency issue (ffmpeg 8.0 + mpv 0.41), where different
        # require two versions of it as a transitive dependency. These versions are internally labelled v7 or v10,
        # respectively, but both have the same filename (`libiconv.2.lib`). We resolve the issue by renaming both files
        # and rewriting all references to use the new names.
        base_id_new = base_id + variant_compat_ver
        canonical_name = best_variant_name.replace(base_id, base_id_new)
        best_variant_path = variant_versions_map[best_variant_name]
        rename_map[canonical_name] = best_variant_path
        canonical_versions_map = canonical_name_map.get(base_id, dict())
        canonical_versions_map[variant_compat_ver] = canonical_name
        canonical_name_map[base_id] = canonical_versions_map
        print(f'Renaming {best_variant_name} compat ver {variant_compat_ver} → {canonical_name}')
      else:
        canonical_versions_map = canonical_name_map.get(base_id, dict())
        canonical_versions_map[variant_compat_ver] = best_variant_name
        canonical_name_map[base_id] = canonical_versions_map
  
  # Create staging directory; copy all libs to be processed into it.
  # This side-steps any thorny issues which might be caused by symlinks, makes purging Frameworks directory easier.
  frameworks_staging_path = os.path.join(frameworks_path, '../FrameworksStaging')
  os.makedirs(frameworks_staging_path, exist_ok=True)
  print(f'Copying {len(canonical_name_map)} libs into {frameworks_staging_path}')
  for base_id, canonical_versions_map in canonical_name_map.items():
    variants_map: dict[str, dict[str, str]] = name_variants_map[base_id]
    for compat_version, variant_versions_map in variants_map.items():
      canonical_name = canonical_versions_map[compat_version]
      
      src_path: str
      if canonical_name in rename_map:
        # Multiple versions found
        src_path = rename_map[canonical_name]
      else:
        src_path = variants_map[compat_version][canonical_name]

      print(f'Canonical name of {base_id} v{compat_version}: {canonical_name}')
      dst = os.path.join(frameworks_staging_path, canonical_name)
      shutil.copyfile(src_path, dst)
  
  # (Optional): Remove unused lib files and links from Frameworks directory.
  # Note: this is not recursive. Sparkle.framework and any other directories will be untouched.
  if len(sys.argv) >= 4 and sys.argv[3] == "purge=yes":
    print(f'Removing old lib files and links from {frameworks_path}')
    old_lib_links = [f for f in os.listdir(frameworks_path) if os.path.islink(os.path.join(frameworks_path, f))]
    for old_lib_link in old_lib_links:
      link_path = os.path.join(frameworks_path, old_lib_link)
      os.unlink(link_path)
    for _, oldlib_path in ls_files_in_dir(frameworks_path):
      os.remove(oldlib_path)
  
  # SECOND PASS: Update install names and lib references.
  # After each file is processed, it is moved from FrameworksStaging to Frameworks.
  print(f'🔧 Normalizing libs for frameworksPath={frameworks_path}')
  for lib_basename, lib_path in ls_files_in_dir(frameworks_staging_path):
    if not (lib_path.endswith('.dylib') or lib_path.endswith('.so')):
      continue
    
    ensure_writable(lib_path)
    ensure_rpath(lib_path)
    print(f"✏️ Setting install_name id on {lib_basename}")
    subprocess.run(['install_name_tool', '-id', f'@rpath/{lib_basename}', lib_path], capture_output=True, text=True)
    
    for ref_path, compat_version, _ in otool_find_nix_libs(lib_path):
      (_, base_id) = parse_base(ref_path)
      if not base_id:
        continue

      sub_canonical_versions_map = canonical_name_map.get(base_id, '')
      if not sub_canonical_versions_map:
        print(f"⚠️ Could not find any canonical versions, skipping id={base_id}")
        continue
      sub_canonical_name = sub_canonical_versions_map.get(compat_version, '')
      if not sub_canonical_name:
        print(f"⚠️ Could not find canonical name for id={base_id}, compatVersion={compat_version}")
        continue
      print(f"🔗 Repointing subdep for {lib_basename}: {ref_path} → @rpath/{sub_canonical_name}")
      rewrite_lib_entry(ref_path, f'@rpath/{sub_canonical_name}', lib_path)
          
    shutil.move(lib_path, os.path.join(frameworks_path, lib_basename))
  
  # Remove staging directory now that all libs have been transferred
  shutil.rmtree(frameworks_staging_path)
  
  # Now process the executable binaries in MacOS directory.
  mac_os_path = os.path.join(app_path, 'Contents/MacOS')
  print(f'🔧 Normalizing executables for {mac_os_path}')
  for exe_base_name, exe_path in ls_files_in_dir(mac_os_path):
    if exe_base_name == ".yt-dlp-wrapped":
      # Is there a way to prevent this file from being generated in the first place?
      print(f"Removing unneeded file: {exe_path}:")
      os.remove(exe_path)
      continue
    
    ensure_rpath(exe_path)
    
    for ref_path, compat_version, _ in otool_find_nix_libs(exe_path):
      (_, base_id) = parse_base(ref_path)
      if not base_id:
        continue

      sub_canonical_versions_map = canonical_name_map.get(base_id, '')
      if not sub_canonical_versions_map:
        print(f"⚠️ Could not find any canonical versions, skipping id={base_id}")
        continue
      sub_canonical_name = sub_canonical_versions_map.get(compat_version, '')
      if not sub_canonical_name:
        continue
      print(f"🔗 Repointing subdep for {exe_base_name}: {ref_path} → @rpath/{sub_canonical_name}")
      rewrite_lib_entry(ref_path, f'@rpath/{sub_canonical_name}', exe_path)

if __name__ == '__main__':
    main()
